version: '3.8'

services:
  # The Application (Frontend + Backend)
  app:
    container_name: lamb_tiger_app_v1
    image: lamb_tiger_game:1.0.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # Ensure you mount your firebase key or provide credentials via env vars in production
    restart: always
